---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: argo-mlops.api.antfield.nl
spec:
  group: api.antfield.nl
  names:
    kind: ArgoMLOps
    plural: ArgoMLOps
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                  description: Image to use when running the workflow

                command:
                  type: array
                  description: Commands to run on executing the image
                  items:
                    type: string

                run_id:
                  type:
                    string
                  nullable: true
                  description: Optional value for setting a run id, auto-created by application if left empty

                models:
                  type: object
                  description: Hyperparameters for model(s) being run
                  properties:
                    json:
                      x-kubernetes-preserve-unknown-fields: true
                      description: Model hyperparameters can be anything, as long as the application can interpret them
