---
images:
  width: 640
  height: 640
  channels: 3
  folder: /mnt/data/Projects/FAFA/img
  # Scraper resume settings
  scraper:
    first_set: 1
    last_set: 5159

  filter:
    exclude:
      - duo
      - swimsuit
      - stereoscopic
      - sportswear
      - underwear

models:
  vae:
    checkpoints:
      folder: /mnt/data/Projects/FAFA/checkpoints

    latent_dim: 2
    batch_size: 24
    epochs: 60

    conv2d:
      - filters: 32
      - filters: 64