---
images:
  width: 640
  height: 640
  channels: 3
  folder: ~/Downloads/FAFA/img
  # Scraper resume settings
  scraper:
    first_set: 1
    last_set: 5159

  filter:
    exclude:
      - duo
      - women
      - detailed
      - distortion
      - holding
      - fighting
      - gun
      - sword
      - spear
      - knife
      - swimsuit
      - drape
      - casual
      - business
      - xmas
      - stereoscopic
      - sportswear
      - underwear
      - overweight
      - chubby
      - grey
      - set_98
      - set_110
      - set_113
      - set_117
      - set_126  # orientation incorrect
      - set_136
      - set_168  # untagged blue chair attribute
      - set_218  # untagged drape attribute
      - set_224  # untagged shawl attributes
      - set_238  # untagged drape attribute
      - set_259  # untagged drape attribute
      - set_261  # untagged pillow attribute
      - set_265  # untagged drape attribute
      - set_275  # untagged drape attribute
      - set_289  # untagged drape attribute
      - set_299  # untagged drape attribute
      - set_325  # untagged ball attribute
      - set_458  # untagged drape attribute
      - set_538  # untagged picture frame attribute
      - set_559  # untagged picture frame attribute
      - set_639  # untagged box attribute
      - set_707  # untagged picture frame attribute
      - set_777  # untagged hat attribute
      - set_878  # untagged swimsuit attribute
      - set_898  # untagged gun attribute
      - set_910  # untagged towel attribute
      - set_923  # untagged hat attribute
      - set_951  # untagged umbrella attribute
      - set_962  # untagged drape attribute
      - set_1069  # untagged hat attribute
      - set_1096  # untagged hat attribute
    # if no values under "include" are specified, it includes all tags
    include:

models:
  vae:
    checkpoints:
      folder: /mnt/data/Projects/FAFA/checkpoints

    latent_dim: 2
    batch_size: 24
    epochs: 60

    conv2d:
      - filters: 32
      - filters: 64