---
images:
  width: 640
  height: 640
  channels: 3
  folder: /mnt/data/Projects/FAFA/img
  # Scraper resume settings
  scraper:
    first_set: 1
    last_set: 5159

  filter:
    exclude:
      - duo
      - detailed
      - holding
      - gun
      - sword
      - spear
      - swimsuit
      - drape
      - casual
      - business
      - stereoscopic
      - sportswear
      - underwear
      - overweight
      - chubby
      - grey
      - darja  # untagged underwear
      - set_98
      - set_110
      - set_113
      - set_117
      - set_126  # orientation incorrect
      - set_136
      - set_168  # untagged blue chair
      - set_218  # untagged drape
      - set_224  # untagged shawls
      - set_238  # untagged drape
      - set_259  # untagged drape
      - set_261  # untagged pillow
      - set_265  # untagged drape
      - set_275  # untagged drape
      - set_289  # untagged drape
      - set_299  # untagged drape
    # if no values under "include" are specified, it includes all tags
    include:

models:
  vae:
    checkpoints:
      folder: /mnt/data/Projects/FAFA/checkpoints

    latent_dim: 2
    batch_size: 24
    epochs: 60

    conv2d:
      - filters: 32
      - filters: 64