---
models:
  vae:
    checkpoints:
      folder: /mnt/data/Projects/FAFA/checkpoints

    latent_dim: 2
    batch_size: 24
    epochs: 60

    conv2d:
      - filters: 32
      - filters: 64

images:
  width: 640
  height: 640
  channels: 3
  folder: ~/Downloads/FAFA/img
  # Scraper resume settings
  scraper:
    first_set: 1
    last_set: 5159

  filter:
    # if no values under "include" are specified, it includes all tags
    include:

    exclude:
      - duo
      - women  # generic tag for multiple person poses
      - detailed
      - distortion
      - holding
      - activities
      - fighting
      - gun
      - sword
      - spear
      - knife
      - swimsuit
      - drape
      - casual
      - business
      - xmas
      - stereoscopic
      - sportswear
      - underwear
      - overweight
      - chubby
      - grey
      - henrieta  # untagged tattoos
      - june      # untagged tattoos
      - billie    # untagged tattoos
      - rosemary  # untagged clothing
      - fannie    # untagged underwear
      - alexej    # male
      - set_98
      - set_110
      - set_113
      - set_117
      - set_126   # orientation incorrect
      - set_136
      - set_168   # untagged blue chair attribute
      - set_218   # untagged drape attribute
      - set_224   # untagged shawl attributes
      - set_238   # untagged drape attribute
      - set_259   # untagged drape attribute
      - set_261   # untagged pillow attribute
      - set_265   # untagged drape attribute
      - set_275   # untagged drape attribute
      - set_289   # untagged drape attribute
      - set_299   # untagged drape attribute
      - set_325   # untagged ball attribute
      - set_458   # untagged drape attribute
      - set_538   # untagged picture frame attribute
      - set_559   # untagged picture frame attribute
      - set_639   # untagged box attribute
      - set_707   # untagged picture frame attribute
      - set_777   # untagged hat attribute
      - set_878   # untagged swimsuit attribute
      - set_898   # untagged gun attribute
      - set_910   # untagged towel attribute
      - set_923   # untagged hat attribute
      - set_951   # untagged umbrella attribute
      - set_962   # untagged drape attribute
      - set_1069  # untagged hat attribute
      - set_1096  # untagged hat attribute
      - set_1145  # untagged book attribute
      - set_1149  # untagged hat attribute
      - set_1154  # untagged hat attribute
      - set_1159  # untagged bottle attribute
      - set_1172  # untagged binoculars attribute
      - set_1192  # untagged bottle attribute
      - set_1213  # untagged hat attribute
      - set_1244  # untagged hat attribute
      - set_1248  # untagged book attribute
      - set_1268  # untagged hat attribute
      - set_1274  # untagged ball attribute
      - set_1311  # untagged ball attribute
      - set_1329  # untagged hat attribute
      - set_1336  # untagged umbrella attribute
      - set_1347  # untagged hat attribute
      - set_1410  # untagged flowers attribute
      - set_1416  # untagged melon attribute
      - set_1433  # untagged sunglasses attribute
      - set_1441  # untagged underwear attribute
      - set_1453  # untagged hat attribute
      # - set_1465  # untagged chair
      # - set_1485  # untagged chair
      # - set_1503  # untagged shoes
      # - set_1507  # untagged chair
      # - set_1509  # untagged chair
      - set_1511  # untagged drape
      # - set_1540  # untagged chair
      # - set_1542  # untagged shoes, chair
      - set_1547  # untagged underwear
      # - set_1549  # untagged chair
      # - set_1577  # untagged shoes
      # - set_1584  # untagged shoes
      # - set_1613  # untagged chair
      # - set_1615  # untagged chair
      # - set_1627  # untagged chair
      - set_1630  # untagged hat attribute
      # - set_1672  # untagged chair
      # - set_1673  # untagged chair
      # - set_1698  # untagged shoes
      # - set_1761  # untagged chair
      - set_1762  # untagged hat attribute
      # - set_1764  # untagged shoes
      # - set_1765  # untagged drape
      - set_1786  # untagged umbrella
      - set_1797  # man
      # - set_1807  # untagged chair
      # - set_1815  # untagged chair, shoes
      # - set_1823  # untagged chair
      # - set_1850  # untagged chair
      # - set_1854  # untagged hat
      # - set_1864  # untagged chair, shoes
      # - set_1865  # untagged hat
      - set_1877  # male
      - set_1895  # untagged drape
      - set_1931  # male
      # - set_1934  # untagged chair
      # - set_1949  # untagged shoes
      # - set_1950  # untagged shoes, chair
      # - set_1965  # untagged chair
      - set_1966  # untagged slab attribute
      # - set_1970  # untagged necklace attribute
      # - set_1980  # untagged chair
      # - set_1981  # untagged chair
      # - set_1989  # untagged chair
      - set_1992  # untagged hat attribute
      # - set_2005  # untagged chair
      # - set_2046  # untagged shoes
      - set_2048  # untagged slab attribute
      - set_2052  # untagged umbrella attribute
      - set_2054  # untagged underwear
      - set_2057  # male
      # - set_2077  # untagged chair
      - set_2102  # untagged hat
      # - set_2109  # untagged shoes, chair
      # - set_2115  # untagged chair
      - set_2130  # untagged hat
      # - set_2132  # untagged shoes
      - set_2141  # untagged umbrella attribute
      # - set_2149  # untagged chair
      # - set_2190  # untagged chair
      # - set_2202  # untagged chair
      # - set_2252  # untagged chair
      # - set_2262  # untagged chair
      # - set_2266  # untagged shoes
      # - set_2426  # untagged chair
      - set_2438  # untagged drape
      # - set_2474  # untagged chair
      - set_2478  # untagged greyscale
      - set_2570  # untagged drape
      # - set_2582  # untagged shoes
      # - set_2618  # untagged shoes
      # - set_2714  # untagged shoes
      # - set_2730  # untagged chair
      # - set_2802  # untagged shoes
      - set_2818  # untagged greyscale
      - set_2921  # untagged drape
      # - set_2925  # untagged shoes
      # - set_2949  # untagged shoes
      # - set_2953  # untagged shoes
      # - set_2977  # untagged shoes
      # - set_3033  # untagged chair
      # - set_3045  # untagged shoes
      - set_3081  # untagged greyscale
      # - set_3121  # untagged shoes
      # - set_3129  # untagged shoes
      # - set_3133  # untagged chair
      # - set_3141  # untagged chair
      # - set_3185  # untagged chair
      # - set_3209  # untagged chair
      # - set_3257  # untagged shoes
      # - set_3273  # untagged shoes
      # - set_3301  # untagged shoes
      - set_3305  # untagged greyscale
      - set_3309  # untagged greyscale
      # - set_3341  # untagged chair
      # - set_3353  # untagged chair
      # - set_3361  # untagged shoes
      # - set_3445  # untagged shoes
      - set_3453  # untagged greyscale
      - set_3457  # untagged greyscale
      - set_3573  # untagged greyscale
      # - set_3621  # untagged shoes
      # - set_3621  # untagged shoes
      # - set_3729  # untagged chair
      # - set_3819  # untagged chair
      # - set_3829  # untagged shoes
      # - set_3869  # untagged chair
      # - set_3961  # untagged chair
      - set_4015  # untagged duo
      # - set_4029  # untagged shoes
      - set_4063  # untagged duo
      # - set_4095  # untagged chair
      # - set_4103  # untagged shoes
      # - set_4107  # untagged chair
      # - set_4119  # untagged chair
      - set_4129  # untagged underwear
      # - set_4131  # untagged chair
      - set_4161  # untagged duo
      - set_4183  # untagged duo
      # - set_4185  # untagged black background
      # - set_4193  # untagged chair
      - set_4209  # untagged duo
      # - set_4217  # untagged black background
      # - set_4219  # untagged black background
      # - set_4221  # untagged shoes
      # - set_4227  # untagged black background
      # - set_4233  # untagged shoes
      # - set_4235  # untagged black background
      # - set_4246  # untagged black background
      # - set_4247  # untagged chair
      # - set_4253  # untagged chair
      # - set_4255  # untagged chair
      - set_4266  # untagged duo
      - set_4271  # untagged duo
      - set_4278  # untagged underwear
      # - set_4280  # untagged shoes
      - set_4283  # untagged duo
      - set_4285  # untagged duo
      # - set_4286  # untagged chair
      # - set_4291  # untagged chair
      # - set_4292  # untagged shoes
      - set_4297  # untagged underwear
      - set_4298  # untagged underwear
      - set_4299  # untagged underwear
      # - set_4308  # untagged shoes, chair
      - set_4312  # untagged grayscale
      # - set_4314  # untagged chair
      # - set_4315  # untagged black background
      - set_4316  # untagged hoop attribute
      - set_4323  # untagged grayscale
      - set_4325  # untagged duo
      # - set_4329  # untagged chair
      # - set_4331  # untagged black background
      # - set_4332  # untagged black background
      - set_4340  # untagged grayscale
      - set_4343  # untagged underwear
      # - set_4344  # untagged black background
      - set_4345  # untagged hoop attribute
      # - set_4346  # untagged black background
      - set_4351  # untagged duo
      - set_4357  # untagged underwear
      # - set_4358  # untagged black background
      # - set_4359  # untagged black background
      # - set_4361  # untagged black background
      # - set_4362  # untagged black background
      # - set_4366  # untagged shoes, chair
      - set_4368  # untagged duo
      # - set_4372  # untagged black background
      # - set_4374  # untagged black background
      # - set_4375  # untagged black background
      # - set_4376  # untagged black background
      # - set_4377  # untagged black background
      # - set_4378  # untagged black background
      - set_4384  # untagged underwear
      - set_4387  # untagged duo
      # - set_4388  # untagged black background
      # - set_4389  # untagged black background
      # - set_4390  # untagged black background
      # - set_4391  # untagged black background
      # - set_4392  # untagged black background
      - set_4398  # untagged duo
      # - set_4402  # untagged black background
      - set_4403  # untagged hoop attribute
      # - set_4404  # untagged black background
      # - set_4405  # untagged black background
      - set_4406  # untagged hoop attribute
      - set_4410  # untagged underwear
      - set_4412  # untagged underwear
      # - set_4417  # untagged black background
      # - set_4418  # untagged black background
      # - set_4419  # untagged black background
      - set_4426  # untagged duo
      # - set_4432  # untagged black background
      # - set_4433  # untagged black background, chair
      # - set_4434  # untagged black background
      # - set_4435  # untagged black background
      # - set_4436  # untagged black background
      # - set_4440  # untagged chair
      - set_4442  # untagged duo
      - set_4444  # untagged underwear
      # - set_4446  # untagged black background
      # - set_4447  # untagged black background
      # - set_4448  # untagged black background
      # - set_4449  # untagged black background
      # - set_4450  # untagged black background
      # - set_4458  # untagged black background
      # - set_4459  # untagged black background
      # - set_4460  # untagged black background
      # - set_4461  # untagged black background, shoes
      - set_4466  # untagged duo
      - set_4468  # untagged underwear
      - set_4471  # wrong image orientation
      # - set_4473  # untagged black background
      # - set_4474  # untagged black background
      # - set_4475  # untagged black background
      # - set_4476  # untagged black background
      # - set_4477  # untagged black background
      # - set_4483  # untagged chair
      # - set_4487  # untagged black background
      # - set_4488  # untagged black background
      # - set_4489  # untagged black background
      # - set_4490  # untagged black background, chair
      # - set_4491  # untagged black background
      - set_4495  # untagged duo
      - set_4500  # untagged underwear
      # - set_4517  # untagged black background
      # - set_4518  # untagged black background
      # - set_4519  # untagged black background
      # - set_4520  # untagged black background
      # - set_4521  # untagged black background, chair
      # - set_4522  # untagged black background
      # - set_4523  # untagged black background
      - set_4530  # untagged underwear
      # - set_4533  # untagged black background
      # - set_4534  # untagged black background
      - set_4535  # untagged ball attribute
      # - set_4536  # untagged black background, chair
      # - set_4538  # untagged black background
      # - set_4540  # untagged shoes
      # - set_4542  # untagged shoes
      # - set_4549  # untagged black background
      # - set_4550  # untagged black background
      # - set_4551  # untagged black background
      # - set_4552  # untagged black background, chair
      # - set_4553  # untagged black background
      # - set_4554  # untagged black background
      # - set_4555  # untagged black background
      # - set_4556  # untagged chair
      # - set_4558  # untagged chair, shoes
      - set_4560  # untagged underwear
      # - set_4565  # untagged black background
      # - set_4566  # untagged black background
      # - set_4567  # untagged black background
      # - set_4568  # untagged black background
      # - set_4569  # untagged black background
      # - set_4570  # untagged black background
      - set_4571  # untagged underwear
      # - set_4575  # untagged chair
      # - set_4576  # untagged chair
      - set_4577  # untagged duo
      # - set_4581  # untagged black background
      # - set_4582  # untagged black background
      # - set_4583  # untagged black background
      # - set_4584  # untagged black background
      # - set_4586  # untagged black background
      # - set_4587  # untagged black background
      - set_4588  # untagged underwear
      - set_4594  # untagged underwear
      - set_4595  # untagged underwear
      - set_4596  # untagged underwear
      # - set_4599  # untagged black background
      # - set_4600  # untagged black background
