---
imgages:
  folder: /mnt/data/Projects/FAFA/img
  # Scraper resume settings
  scraper:
    first_set: 1
    last_set: 5159

  filter:
    exclude:
      - duo
      - swimsuit
      - stereoscopic

checkpoints:
  folder: /mnt/data/Projects/FAFA/checkpoints

models:
  vae:
    epochs: 60
