customResourceDefinition:
  # The kind or name to give to your own custom resource
  kind: ArgoMLOps
  # The crd "shortname"
  abbreviation: mlops
  # The API group name to attach your custom resource definition to
  apiGroup: api.antfield.nl

  serviceAccount:
    name: mlops-sa
    # This must reference the service account name that allows to run Argo Workflows
    workflowServiceAccountName: argo-workflow

  namespaces:
    - operators
    - data

templateRef:
  name: tensorflow-gke-workflow
  entrypoint: main