---
customResourceDefinition:
  # The kind or name to give to your own custom resource
  kind: ArgoMLOps
  # The crd "shortname"
  abbreviation: argomlops
  # The API group name to attach your custom resource definition to
  apiGroup: api.antfield.nl

  serviceAccount:
    name: mlops-sa
    # This must reference the service account name that allows to run Argo Workflows
    workflowServiceAccountName: argo-workflow

  gcsSecret:
    name: gcs-secret
    key: serviceAccountKey

  manifestConfigMap:
    name: mlops-manifest

  namespaces:
    - operators
    - data

  dataVolumes:
    - name: mlops-data-volume
      storageClass: standard
      reclaimPolicy: Retain
      capacity: 15 GiB

eventBus:
  name: argomlops-default

templateRef:
  name: tensorflow-workflow-template
  template: main
