---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: {{ .Values.customResourceDefinition.kind | lower }}.{{ .Values.customResourceDefinition.apiGroup }}
spec:
  group: {{ .Values.customResourceDefinition.apiGroup }}
  names:
    kind: {{ .Values.customResourceDefinition.kind }}
    singular: {{ .Values.customResourceDefinition.kind | lower }}
    plural: {{ .Values.customResourceDefinition.kind | lower }}
    listKind: {{ .Values.customResourceDefinition.kind }}List
    shortNames:
      - {{ .Values.customResourceDefinition.abbreviation }}
  scope: Namespaced

  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:

                image:
                  type: string
                  description: Base image to use when running the workflow

                repository:
                  type: string
                  description: Source for the application to check out and run in the image

                command:
                  type: string
                  description: Command to run on executing the image

                run_id:
                  type:
                    string
                  nullable: true
                  description: Optional value for setting a run id, auto-created by application if left empty

                models:
                  type: object
                  description: Hyperparameters for model(s) being run
                  x-kubernetes-preserve-unknown-fields: true
                  properties:
                    json:
                      x-kubernetes-preserve-unknown-fields: true
                      description: Model hyperparameters can be anything, it's up to the application can interpret them

                data:
                  type: object
                  description: Settings for data loading and transformation
                  x-kubernetes-preserve-unknown-fields: true
                  properties:
                    json:
                      x-kubernetes-preserve-unknown-fields: true
                      description: Data settings can be anything, it's up to the application can interpret them
