---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: {{ .Values.customResourceDefinition.kind | lower }}.{{ .Values.customResourceDefinition.apiGroup }}
spec:
  group: {{ .Values.customResourceDefinition.apiGroup }}
  names:
    kind: {{ .Values.customResourceDefinition.kind }}
    singular: {{ .Values.customResourceDefinition.kind | lower }}
    plural: {{ .Values.customResourceDefinition.kind | lower }}
    listKind: {{ .Values.customResourceDefinition.kind }}List
    shortNames:
      - {{ .Values.customResourceDefinition.abbreviation }}
  scope: Namespaced

  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                  description: Image to use when running the workflow

                command:
                  type: array
                  description: Commands to run on executing the image
                  items:
                    type: string

                run_id:
                  type:
                    string
                  nullable: true
                  description: Optional value for setting a run id, auto-created by application if left empty

                models:
                  type: object
                  description: Hyperparameters for model(s) being run
                  properties:
                    json:
                      x-kubernetes-preserve-unknown-fields: true
                      description: Model hyperparameters can be anything, as long as the application can interpret them
