{{- range $volume := $.Values.customResourceDefinition.dataVolumes }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $volume.name }}-claim
spec:
  resources:
    requests:
      storage: {{ $volume.capacity }}
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ $volume.storageClass }}
{{- end }}
