{{- range $namespace := .Values.customResourceDefinition.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "argo-mlops-operator.fullname" $ }}-{{ $.Values.customResourceDefinition.kind | lower }}
  namespace: {{ $namespace }}
rules:
  - apiGroups:
      - {{ $.Values.customResourceDefinition.apiGroup }}
    resources:
      - {{ $.Values.customResourceDefinition.kind | lower }}
    verbs:
      - get
      - list
      - watch
  # Grant rights to operate on workflows
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - get
      - create
      - list
      - watch
      - patch
{{- end }}
