{{- range $namespace := .Values.customResourceDefinition.namespaces }}
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: {{ $.Values.customResourceDefinition.kind | lower }}-sensor
  namespace: {{ $namespace }}
spec:
  eventBusName: {{ $.Values.eventBus.name }}
  template:
    serviceAccountName: {{ $.Values.customResourceDefinition.serviceAccount.name }}
  dependencies:
    - name: source-dependency
      # References the metadata.name in the event source
      eventSourceName: {{ $.Values.customResourceDefinition.kind | lower }}-source
      # References the key directly under "resource:" in the event source
      eventName: {{ $.Values.customResourceDefinition.kind | lower }}
  triggers:
    - template:
        name: argo-mlops-trigger
        argoWorkflow:
          operation: submit
          parameters:
            - src:
                dependencyName: source-dependency
                dataKey: body
              dest: spec.arguments.parameters.0.value
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: process-{{ $.Values.customResourceDefinition.kind | lower }}-
              spec:
                serviceAccountName: {{ $.Values.customResourceDefinition.serviceAccount.workflowServiceAccountName }}
                entrypoint: deploy
                arguments:
                  parameters:
                    # the values will get overridden by event payload from below
                    - name: mlops-manifest
                      value: ""
                templates:
                  - name: deploy
                    steps:
                      - - name: apply-configmap-step
                          template: configmap-operate
                          arguments:
                            parameters:
                              - name: mlops-manifest
                                value: "{{`{{workflow.parameters.mlops-manifest}}`}}"
                              - name: action
                                value: apply

                      - - name: call-gpu-validate-template
                          templateRef:
                            name: validate-gpu-workflow-template
                            template: validate-gpu

                      - - name: call-script-template
                          templateRef:
                            {{- $.Values.templateRef | toYaml | nindent 28 }}

                      - - name: delete-configmap-step
                          template: configmap-operate
                          arguments:
                            parameters:
                              - name: mlops-manifest
                                value: "{{`{{workflow.parameters.mlops-manifest}}`}}"
                              - name: action
                                value: delete

                  - name: configmap-operate
                    inputs:
                      parameters:
                        - name: mlops-manifest
                          value: ""
                        - name: action
                          value: apply
                    resource:
                      action: "{{`{{inputs.parameters.action}}`}}"
                      manifest: |
                        apiVersion: v1
                        kind: ConfigMap
                        metadata:
                          name: {{ $.Values.customResourceDefinition.manifestConfigMap.name }}
                        data:
                          config.json: |
                            {{`{{inputs.parameters.mlops-manifest}}`}}
{{- end }}
