{{- range $namespace := .Values.customResourceDefinition.namespaces }}
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: tensorflow-workflow-template
  namespace: {{ $namespace }}
  generateName: tensorflow-check-
spec:
  serviceAccountName: argo-workflow
  tolerations:
    - key: nvidia.com/gpu
      value: present
      effect: NoSchedule

  entrypoint: main

  arguments:
    parameters:
      # Injected by Sensor workflow
      - name: mlops-manifest
        # Sets a compact default which we can test-run in Argo UI
        default: |
          { "apiVersion": "api.antfield.nl/v1alpha1", "kind": "ArgoMLOps",
            "metadata": { "name": "mlops-test", "namespace": "data" },
            "spec": {
              "image": "python3.10:minimal",
              "repository": "https://github.com/Antfield-Creations/fafa-vae",
              "command": "python3 --version"
          } }

  templates:
    - name: main

      volumes:
        - name: manifest
          configMap:
            name: "{{ $.Values.customResourceDefinition.manifestConfigMap.name }}"
            items:
              - key: config.json
                path: config.json
        - name: gcs
          secret:
            secretName: {{ $.Values.customResourceDefinition.gcsSecret.name }}
            items:
              - key: {{ $.Values.customResourceDefinition.gcsSecret.key }}
                path: {{ $.Values.customResourceDefinition.gcsSecret.key }}
  {{- range $volume := $.Values.customResourceDefinition.dataVolumes }}
        - name: {{ $volume.name }}
          persistentVolumeClaim:
            claimName: {{ $volume.name }}-claim
  {{- end }}

      container:
        resources:
          limits:
            nvidia.com/gpu: "1"
        image: tensorflow/tensorflow:2.8.1-gpu
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /mnt/gcsSecret/{{ $.Values.customResourceDefinition.gcsSecret.key }}
        volumeMounts:
          - name: manifest
            mountPath: /mnt/manifest
          - name: gcs
            mountPath: /mnt/gcsSecret
  {{- range $volume := $.Values.customResourceDefinition.dataVolumes }}
          - name: {{ $volume.name }}
            mountPath: /mnt/{{ $volume.name }}
  {{- end }}
        command:
          - bash
          - -c
        args:
          - |
            set -eux pipefail

            # Install json cli parser
            curl -fsSL https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 -o /usr/bin/jq
            chmod +x /usr/bin/jq

            # Install Git and basic dependencies
            rm /etc/apt/sources.list.d/cuda.list
            rm /etc/apt/sources.list.d/nvidia-ml.list
            apt-key del 7fa2af80
            curl -fsSLO https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-keyring_1.0-1_all.deb
            dpkg -i cuda-keyring_1.0-1_all.deb
            add-apt-repository ppa:deadsnakes/ppa
            apt-get update
            apt-get install -y git python3.9

            # Clone into current directory
            mkdir script
            cd script
            git clone $(jq -r .spec.repository /mnt/manifest/config.json) .

            # Write script config overrides to config.yaml
            cp /mnt/manifest/config.json ./config.json
            echo config.json

            # install dependency manager and run main script
            pip3 install pipenv
            eval $(jq -r .spec.command config.json)
{{- end }}
