{{- range $namespace := .Values.customResourceDefinition.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "argo-mlops-operator.fullname" $ }}-{{ $.Values.customResourceDefinition.kind | lower }}-workflows-extras
  namespace: {{ $namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
{{- end }}
