---
name: Test

on:   # yamllint disable-line
#  - push
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SA }}'

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: install dependency manager
        run: pip install --user pipenv

      - name: install dependencies
        run: pipenv install --dev

      - name: Run checks
        run: make check

      - name: Run tests
        run: make tests
